### ISSUE TITLE
parsing RDF+XML into application/ld+json is not working

### ISSUE THREAD

**Issue by biborno** [linkeddata/rdflib.js#120]
I am trying to read RDF+XML data and convert it into application/ld+json format. It works for application/turtle format. however for application/ld+json,  there is error.

Here is my source:
//solved reading rdf/xml from a file to rdflib graph
```
var fs = require('fs'),
    $rdf = require('rdflib');

var rdfData=fs.readFileSync(__dirname+'/1.xml').toString();

var store=$rdf.graph();
var contentType='application/rdf+xml';
var baseUri="http://IoFTriples.com";
var targetContentType = 'application/ld+json'; // possible options: application/rdf+xml;text/n3;text/turtle;application/x-turtle;application/n3;application/ld+json;application/n-quads or nquads'
try{
    var srcData=$rdf.parse(rdfData,store,baseUri,contentType);
    var targetData = $rdf.serialize(srcData, store, baseUri, targetContentType);
    console.log(targetData);

    /*var stms = store.statementsMatching(undefined, undefined , undefined);
    for (var i=0; i<stms.length;i++) {
        var stm = stms[i]
        console.log(stm) // the WebID of a friend

    }*/
} catch(err){
    console.log(err);
```
the 1.xml file is here. (it works perfectly if i try to parse into turtle
```
<rdf:RDF
    xmlns:rdf="http://www.w3.org/1999/02/22-rdf-syntax-ns#"
    xmlns:oneM2M="http://www.onem2m.org/ontology/Base_Ontology#"
    xmlns:owl="http://www.w3.org/2002/07/owl#"
    xmlns:rdfs="http://www.w3.org/2000/01/rdf-schema#"
    xmlns:cfso="http://203.254.173.81:8080/ontologies/ConnectedFarmServiceOntology.owl#"
    xmlns:xsd="http://www.w3.org/2001/XMLSchema#">
  <oneM2M:Thing rdf:about="http://203.254.173.81:8080/ontologies/ConnectedFarmServiceOntology.owl#KETICF">
    <cfso:hasSpecies>
      <cfso:Species rdf:about="http://203.254.173.81:8080/ontologies/ConnectedFarmServiceOntology.owl#Type1"/>
    </cfso:hasSpecies>
    <cfso:hasSPName>
      <cfso:SPName rdf:about="http://203.254.173.81:8080/ontologies/ConnectedFarmServiceOntology.owl#Maxfor"/>
    </cfso:hasSPName>
    <cfso:hasLocation>
      <cfso:Location rdf:about="http://203.254.173.81:8080/ontologies/ConnectedFarmServiceOntology.owl#Buyeo"/>
    </cfso:hasLocation>
    <cfso:hasCropName>
      <cfso:CropName rdf:about="http://203.254.173.81:8080/ontologies/ConnectedFarmServiceOntology.owl#CharryTomato">
        <cfso:hasSpecies rdf:resource="http://203.254.173.81:8080/ontologies/ConnectedFarmServiceOntology.owl#Type1"/>
      </cfso:CropName>
    </cfso:hasCropName>
    <cfso:hasControlMode>
      <cfso:ControlMode rdf:about="http://203.254.173.81:8080/ontologies/ConnectedFarmServiceOntology.owl#A"/>
    </cfso:hasControlMode>
  </oneM2M:Thing>
</rdf:RDF>
```
the output is here:
```
"C:\Program Files (x86)\JetBrains\WebStorm 11.0.3\bin\runnerw.exe" "C:\Program Files\nodejs\node.exe" rdflibTutorial.js
undefined
d:\WorkSpace\sparqltest\node_modules\rdflib\dist\rdflib-node.js:10949
      jsonCallback(null, jsonString)
      ^

TypeError: jsonCallback is not a function
    at d:\WorkSpace\sparqltest\node_modules\rdflib\dist\rdflib-node.js:10949:7
    at fn (d:\WorkSpace\sparqltest\node_modules\rdflib\node_modules\async\lib\async.js:638:34)
    at Immediate._onImmediate (d:\WorkSpace\sparqltest\node_modules\rdflib\node_modules\async\lib\async.js:554:34)
    at processImmediate [as _immediateCallback] (timers.js:383:17)

Process finished with exit code 1
```

**Comment by biborno** [comment]
for application/ld+json I need to pass a call back function which should receive two parameters.
source:
```
//solved reading rdf/xml from a file to rdflib graph
var fs = require('fs'),
    $rdf = require('rdflib');

var rdfData=fs.readFileSync(__dirname+'/1.xml').toString();

var store=$rdf.graph();
var contentType='application/rdf+xml';
var baseUri="http://IoFTriples.com";
var targetContentType = 'application/ld+json'; // possible options: application/rdf+xml;text/n3;text/turtle;application/x-turtle;application/n3;application/ld+json;application/n-quads or nquads'
try{
    var srcData=$rdf.parse(rdfData,store,baseUri,contentType);
    var targetData = $rdf.serialize(srcData, store, baseUri, targetContentType,function(err,jsonString){
        console.log(JSON.parse(jsonString));
    });
    console.log(targetData);

    /*var stms = store.statementsMatching(undefined, undefined , undefined);
    for (var i=0; i<stms.length;i++) {
        var stm = stms[i]
        console.log(stm) // the WebID of a friend

    }*/
} catch(err){
    console.log(err);
}
```

**Comment by jamsden** [comment]
Last I looked, rdflib.js did not support a JSON-LD serializer. It uses jsonld.js to parse JSON-LD and then converts the jsonld.js internal format to rdflib.js internal format, but the other direction wasn’t implemented.

**Comment by biborno** [comment]
@jamsden Thanx a lot. Actually when I checked the source rdflib-node.js what i found:
```
//   Serialize to the appropriate format
//
// Either
//
// @@ Currently NQuads and JSON/LD are deal with extrelemently inefficiently
// through mutiple conversions.
//
$rdf.serialize = function (target, kb, base, contentType, callback) {
  var documentString = null
  try {
    var sz = $rdf.Serializer(kb)
    var newSts = kb.statementsMatching(undefined, undefined, undefined, target)
    var n3String
    sz.suggestNamespaces(kb.namespaces)
    sz.setBase(base)
    switch (contentType) {
      case 'application/rdf+xml':
        documentString = sz.statementsToXML(newSts)
        return executeCallback(null, documentString)
      case 'text/n3':
      case 'text/turtle':
      case 'application/x-turtle': // Legacy
      case 'application/n3': // Legacy
        documentString = sz.statementsToN3(newSts)
        return executeCallback(null, documentString)
      case 'application/ld+json':
        n3String = sz.statementsToN3(newSts)
        $rdf.convert.convertToJson(n3String, callback)
        break
      case 'application/n-quads':
      case 'application/nquads': // @@@ just outpout the quads? Does not work for collections
        n3String = sz.statementsToN3(newSts)
        documentString = $rdf.convert.convertToNQuads(n3String, callback)
        break
      default:
        throw new Error('Serialize: Content-type ' + contentType + ' not supported for data write.')
    }
  } catch (err) {
    if (callback) {
      return (err)
    }
    throw err // Don't hide problems from caller in sync mode
  }
```

after seeing the switch case I thought it worked.

**Comment by jamsden** [comment]
Ok, it looks like this has been added since I looked last year. The issue is that n3.js, jsonld.js and rdflib.js all use a similar, but different internal representation of a collection of triples. This makes it difficult to use these together. There should be an effort to normalize these three in order to support a core set of RDF capabilities in JavaScript.

Ruby has a lot better RDF support.
