### ISSUE TITLE
Fix cyclic dependency in term.js and collection.js

### ISSUE THREAD

**Issue by dmitrizagidulin** [linkeddata/rdflib.js#139]
To reproduce current error:

```bash
node
> require('./index').graph().any([])
TypeError: Collection is not a constructor
    at term (/Users/dmitri/code/_Solid/rdflib.js/src/term.js:24:13)
    at IndexedFormula.statementsMatching (/Users/dmitri/code/_Solid/rdflib.js/src/indexed-formula.js:634:31)
    at IndexedFormula.anyStatementMatching (/Users/dmitri/code/_Solid/rdflib.js/src/indexed-formula.js:269:18)
    at IndexedFormula.any (/Users/dmitri/code/_Solid/rdflib.js/src/formula.js:29:19)
    at repl:1:13
    at REPLServer.defaultEval (repl.js:272:27)
    at bound (domain.js:280:14)
    at REPLServer.runBound [as eval] (domain.js:293:12)
    at REPLServer.<anonymous> (repl.js:441:10)
    at emitOne (events.js:101:20)
```

**Comment by dmitrizagidulin** [comment]
Fixed. Closing.
