### ISSUE TITLE
XML qname parses correctly but is not serialized correctly.

### ISSUE THREAD

**Issue by jamsden** [linkeddata/rdflib.js#228]
Error: Invalid character "." cannot be in XML qname for URI: http://jazz.net/xmlns/prod/jazz/rtc/ext/1.0/com.ibm.team.apt.attribute.acceptance
at Serializer.qnameMethod (/Users/jamsden/GitHub/rdflib.js/lib/serializer.js:913:17)
at Serializer.subjectXMLTreeMethod (/Users/jamsden/GitHub/rdflib.js/lib/serializer.js:819:13)
at Serializer.statementListToXMLTreeMethod (/Users/jamsden/GitHub/rdflib.js/lib/serializer.js:736:22)
at Serializer.statementsToXML (/Users/jamsden/GitHub/rdflib.js/lib/serializer.js:931:16)
at Object.serialize (/Users/jamsden/GitHub/rdflib.js/lib/serialize.js:27:29)

According to https://www.w3.org/TR/REC-xml/#NT-Name, NCName can contain ".". So the serializer should handle these QNames.

**Comment by jamsden** [comment]
For the syntax of a QName, https://www.w3.org/TR/REC-xml/ says that a local name for a qname is a Name less colon. A Name is defined here: https://www.w3.org/TR/REC-xml/#NT-Name. There's almost nothing illegal in that set of characters except colon, control characters, and unassigned code points (and as far as I can see the latter are merely discouraged, not illegal).

**Comment by jamsden** [comment]
I see this is still open.  https://www.w3.org/TR/xml-names11/#NT-NCName explicitly states that "." is included in NCName which is part of a Prefix. 

The fix is simple: In rdflib/src/serializer.js:196:
Change:
  __Serializer.prototype._notQNameChars = '\t\r\n !"#$%&\'()*.,+/;<=>?@[\\]^`{|}~';
to:
  __Serializer.prototype._notQNameChars = '\t\r\n !"#$%&\'()*,+/;<=>?@[\\]^`{|}~';
(i.e., remove . from the _notQNameChars)

Any chance this could get addressed?

**Comment by bourgeoa** [comment]
Thanks for reopening.
But this other consequences that make some tests fail on serialize text/turtle
see https://github.com/linkeddata/rdflib.js/pull/686

**Comment by jamsden** [comment]
Understood. But given that, is this something that could be addressed in a future release or do I need to fork?

**Comment by bourgeoa** [comment]
@TallTed thanks I shall try to remember.
