### ISSUE TITLE
IndexedFormula is not RDFJS-compliant

### ISSUE THREAD

**Issue by rubensworks** [linkeddata/rdflib.js#238]
`IndexedFormula#match` seems to have been designed to be compliant with the [RDFJS Source interface](http://rdf.js.org/#source-interface). However, when passing terms that were created by a different datafactory, the following error occurs:
```
(node:13101) UnhandledPromiseRejectionWarning: TypeError: term.hashString is not a function
    at IndexedFormula.canon (/Users/rtaelman/Documents/UGent/nosync/solid/solid-permissions/node_modules/rdflib/lib/indexed-formula.js:365:38)
    at IndexedFormula.statementsMatching (/Users/rtaelman/Documents/UGent/nosync/solid/solid-permissions/node_modules/rdflib/lib/indexed-formula.js:813:27)
    at IndexedFormula.match (/Users/rtaelman/Documents/UGent/nosync/solid/solid-permissions/node_modules/rdflib/lib/indexed-formula.js:518:19)
```

It looks like `IndexedFormula` is making some assumptions regarding the availability of functions in terms that fall outside of the [RDFJS spec](http://rdf.js.org/#term-interface).
In this case, the `hashString` function is called, which exists on rdflib terms, but is not defined in the RDFJS spec, so this fails when other datafactories are used.

One solution would be to detach `hashString` from the `Node` class, so that it can be used for any RDFJS term. I'm no expert on the internals of rdflib, so please let me know if there are better solutions. I'd be happy to send in a PR for this.

**Comment by jeswr** [comment]
Closing: the reported defect is fixed on main. `IndexedFormula.canon` (src/store.ts:505) and the canonical data factory's `id()` (src/factories/canonical-data-factory.ts:97) no longer require rdflib-specific `term.hashString()` on incoming terms — index keys are derived from the term's RDF/JS shape — so `match()` / `statementsMatching()` now accept terms created by other RDF/JS data factories. Verified at runtime against v2.4.0 with foreign-factory terms as part of the #824 triage.

Broader RDF/JS Source/Store conformance (streaming `match`, full interface guarantees) is tracked separately under #374 and the #824 store-rework track.
