### ISSUE TITLE
Error while serializing to json-ld

### ISSUE THREAD

**Issue by gfellerph** [linkeddata/rdflib.js#303]
I'm trying to serialize the pim space ontology to json-ld. To accomplish this, I'm using the following script:

`test.js`
```node
const rdflib = require('rdflib');
const store = rdflib.graph();
const uri = 'http://www.w3.org/ns/pim/space#';
const fs = require('fs');

const pimspace = fs.readFileSync('./pimspace.ttl', 'utf-8');

rdflib.parse(pimspace, store, uri, 'text/turtle');
rdflib.serialize(null, store, uri, 'application/ld+json', (err, data) => {
  if (err) {
    console.log(err);
    return err;
  }
  console.log(data);
  return data;
});
```

`pimspace.ttl` (dowload it [here](https://www.w3.org/ns/pim/space#))

When I run the script with `node test.js`, it produces the following error:

```shell
{ jsonld.ParseError: Error while parsing N-Quads; invalid quad.
    at _parseNQuads (C:\Projects\whattheontology\node_modules\rdflib\node_modules\jsonld\js\jsonld.js:6964:13)
    at C:\Projects\whattheontology\node_modules\rdflib\node_modules\jsonld\js\jsonld.js:881:17
    at processTicksAndRejections (internal/process/next_tick.js:74:9)
  name: 'jsonld.ParseError',
  message: 'Error while parsing N-Quads; invalid quad.',
  details: { line: 35 } }
```

The turtle document seems valid, according to this [ttl validator](http://ttl.summerofcode.be/).

**Comment by tuelsch** [comment]
Also, a similar error occurs when trying to parse https://www.w3.org/1999/02/22-rdf-syntax-ns# and serialize it to `application/ld+json`:

**Comment by angelo-v** [comment]
Tested both examples with rdflib 2.2.37 and they work
