### ISSUE TITLE
npm run build:types is broken

### ISSUE THREAD

**Issue by michielbdejong** [linkeddata/rdflib.js#442]
throwing errors in master
I think this is/was causing the npm package to be unbuilt, I tagged a patch version now but `npm publish`  fails at the rdflib@1.3.2 build:types script.

**Comment by sroze** [comment]
`build:types` seems to be working for me, but `npm publish` is failing at another step:
```

> rdflib@2.1.2 prepublishOnly .
> npm ci && npm run build && npm run build:types && npm run build:browser && npm run build:esm

npm WARN prepare removing existing node_modules/ before installation

> fsevents@1.2.13 install /Users/samuelroze/git/rdflib.js/node_modules/fsevents
> node install.js

  SOLINK_MODULE(target) Release/.node
  CXX(target) Release/obj.target/fse/fsevents.o
  SOLINK_MODULE(target) Release/fse.node

> core-js@2.6.11 postinstall /Users/samuelroze/git/rdflib.js/node_modules/core-js
> node -e "try{require('./postinstall')}catch(e){}"

added 868 packages in 12.775s

> rdflib@2.1.2 build /Users/samuelroze/git/rdflib.js
> babel src --extensions ".ts,.js" -d lib

Successfully compiled 46 files with Babel (2848ms).

> rdflib@2.1.2 build:types /Users/samuelroze/git/rdflib.js
> tsc --emitDeclarationOnly -d --moduleResolution node --declarationDir lib --allowJs false


> rdflib@2.1.2 build:browser /Users/samuelroze/git/rdflib.js
> webpack --progress

[webpack-cli] Error: Universal Chunk Loading is not implemented yet
    at EnableChunkLoadingPlugin.apply (/Users/samuelroze/git/rdflib.js/node_modules/webpack/lib/javascript/EnableChunkLoadingPlugin.js:102:12)
    at WebpackOptionsApply.process (/Users/samuelroze/git/rdflib.js/node_modules/webpack/lib/WebpackOptionsApply.js:139:40)
    at createCompiler (/Users/samuelroze/git/rdflib.js/node_modules/webpack/lib/webpack.js:78:28)
    at create (/Users/samuelroze/git/rdflib.js/node_modules/webpack/lib/webpack.js:115:15)
    at webpack (/Users/samuelroze/git/rdflib.js/node_modules/webpack/lib/webpack.js:123:46)
    at f (/Users/samuelroze/git/rdflib.js/node_modules/webpack/lib/index.js:35:15)
    at WebpackCLI.createCompiler (/Users/samuelroze/git/rdflib.js/node_modules/webpack-cli/lib/webpack-cli.js:176:24)
    at WebpackCLI.run (/Users/samuelroze/git/rdflib.js/node_modules/webpack-cli/lib/webpack-cli.js:268:25)
    at async runCLI (/Users/samuelroze/git/rdflib.js/node_modules/webpack-cli/lib/bootstrap.js:59:9)
```

**Comment by michielbdejong** [comment]
Thanks! Fixed this with `npm install --save-dev webpack@4`
