### ISSUE TITLE
RDF/XML syntax error No namespace for rdf:about

### ISSUE THREAD

**Issue by nicola** [linkeddata/rdflib.js#47]
I have been trying with 5 different files and this code:

``` javascript
request('http://schema.rdfs.org/all.rdf', function(err, response, body) {
    var kb = new $rdf.IndexedFormula();
    $rdf.parse(body, kb, 'http://schema.rdfs.org/all.rdf', 'application/rdf+xml');
    console.log(kb)
  });
```

but I get:

```
Error trying to parse <http://schema.rdfs.org/all.rdf> as application/rdf+xml:
Error: RDF/XML syntax error: No namespace for rdf:about in http://schema.rdfs.org/all.rdf:
Error: RDF/XML syntax error: No namespace for rdf:about in http://schema.rdfs.org/all.rdf
    at null.<anonymous> (/Users/mozilla/Proj/schemas/node_modules/rdflib/dist/rdflib.js:1698:23)
    at parseDOM (/Users/mozilla/Proj/schemas/node_modules/rdflib/dist/rdflib.js:1828:38)
    at parse (/Users/mozilla/Proj/schemas/node_modules/rdflib/dist/rdflib.js:1688:14)
    at Object.parse (/Users/mozilla/Proj/schemas/node_modules/rdflib/dist/rdflib.js:8221:20)
    at Request._callback (/Users/mozilla/Proj/schemas/index.js:16:10)
    at Request.self.callback (/Users/mozilla/Proj/schemas/node_modules/request/request.js:372:22)
    at Request.emit (events.js:98:17)
    at Request.<anonymous> (/Users/mozilla/Proj/schemas/node_modules/request/request.js:1317:14)
    at Request.emit (events.js:117:20)
    at IncomingMessage.<anonymous> (/Users/mozilla/Proj/schemas/node_modules/request/request.js:1265:12)
```

Am I parsing the right way?

**Comment by ckristo** [comment]
Hi, same problem here when trying to load a local RDF/XML file -- rapper parses it without complaints; @nicola did you solve the problem somehow?

**Comment by ckristo** [comment]
Ok, seems to be a problem with the use of jsdom, replaced jsdom with xmldom in `util.js` and the parser works fine:
````
$rdf.Util.parseXML = function(str) {
    var dparser;
    if ((typeof tabulator != 'undefined' && tabulator.isExtension)) {
        dparser = Components.classes["@mozilla.org/xmlextras/domparser;1"].getService(
                    Components.interfaces.nsIDOMParser);
    } else if (typeof module != 'undefined' && module && module.exports){ // Node.js
        //var libxmljs = require('libxmljs'); // Was jsdom before 2012-01 then libxmljs but that nonstandard
        //return libxmljs.parseXmlString(str);
        //var jsdom = require('jsdom');
        //var dom = jsdom.jsdom(str, undefined, {} );// html, level, options
        //return dom
        var DOMParser = require('xmldom').DOMParser;
        var dom = new DOMParser().parseFromString(str,'text/xml')
        return dom
    } else {
        dparser = new DOMParser();
    }
    return dparser.parseFromString(str, 'application/xml');
};
````
This shouldn't be a problem for RDF/XML, but as far as I saw, the function `parseXML` was also used to parse RDFa in the fetcher. Due to the fact that RDFa can be used with HTML (that must not be valid XML), I think this needs further work. Maybe just use jsdom again for parsing when the fetcher detects RDFa?

**Comment by ckristo** [comment]
somehow also related: #67

**Comment by ckristo** [comment]
A patched version that makes use of xmldom can be found here: https://github.com/ckristo/rdflib.js/tree/xmldom

**Comment by ckristo** [comment]
Tried once more to use jsdom for parsing, but with no luck. jsdom does assign wrong namespaces (e.g. for the `rdf:RDF` element it assigns some HTML namespace instead of the RDF one)

**Comment by jamsden** [comment]
I tried the patched version above, but still get the error. Perhaps I don't understand what the base URI parameter should be. Here's what I'm doing:
	rskb = new rdflib.IndexedFormula();
	rdflib.parse(rdfSource, rskb, 'https://oslclnx2.rtp.raleigh.ibm.com:9443/ccm/rootservices', 'application/rdf+xml');
... attempting to read an RTC rootservices document. Here's the first few lines of that document:
<?xml version="1.0"?>
 

 
<rdf:Description
xmlns:rdf="http://www.w3.org/1999/02/22-rdf-syntax-ns#"
xmlns:dc="http://purl.org/dc/terms/"
xmlns:jfs="http://jazz.net/xmlns/prod/jazz/jfs/1.0/"
xmlns:jd="http://jazz.net/xmlns/prod/jazz/discovery/1.0/"
xmlns:jdb="http://jazz.net/xmlns/prod/jazz/dashboard/1.0/"
xmlns:jp06="http://jazz.net/xmlns/prod/jazz/process/0.6/"
xmlns:jp="http://jazz.net/xmlns/prod/jazz/process/1.0/"
xmlns:jtp="http://jazz.net/xmlns/prod/jazz/jtp/0.6/"
xmlns:ju="http://jazz.net/ns/ui#"
xmlns:oslc="http://open-services.net/ns/core#"
xmlns:trs="http://jazz.net/ns/trs#"
xmlns:trs2="http://open-services.net/ns/core/trs#"
rdf:about="https://oslclnx2.rtp.raleigh.ibm.com:9443/ccm/rootservices">
 
As you can see, rdf:about does have a namespace.
Am I using the correct base parameter?

**Comment by jamsden** [comment]
OK, I have it parsing OK now.

**Comment by ckristo** [comment]
@jamsden Any problems with my patch I should fix?

**Comment by ckristo** [comment]
btw: [rdf-ext](https://github.com/zazukoians/rdf-ext) uses a fork of rdflib.js' RDF/XML Parser that also uses xmldom instead, see https://github.com/zazukoians/rdf-ext/blob/master/lib/rdfxml-parser.js and https://github.com/zazukoians/rdf-ext/blob/master/lib/utils-node.js

**Comment by jeswr** [comment]
Closing as part of the maintainer-signed-off triage (plan #824). Verified on the current release (v2.4.0) that RDF/XML with rdf:about parses correctly — rdflib now uses @xmldom/xmldom, which was the fix identified in this thread, and the original error no longer reproduces. Please reopen with a fresh repro if you hit RDF/XML namespace errors on a current release.
