### ISSUE TITLE
$rdf.fetch local file -- node hangs until timeout is reached

### ISSUE THREAD

**Issue by ckristo** [linkeddata/rdflib.js#68]
Hi,

I encountered that when loading a local file with a fetcher, node hangs until the timeout is reached. Is that intended behavior? Example:
````
// - load RDF file
var fetch = $rdf.fetcher(kb, 5000);
fetch.nowOrWhenFetched('file:foaf.rdf', undefined, function(ok) { /* ... */ });
````

(node.js v0.12.6, latest version of rdflib.js + patched RDF/XML parsing, see #47)

For those who encounter the same problem and need a quick work-around -- you could use node IO to read the file and use the parser directly. Example:
````
// - load RDF file
fs.readFile('foaf.rdf', function (err, data) {
    if (err) { /* error handling */ }
    // - parse RDF file
    $rdf.parse(data.toString(), kb, 'foaf.rdf', 'application/rdf+xml', function(err, kb) { /* ... */ });
````

**Comment by ckristo** [comment]
It doesn't seem to matter if I load a local file or an URI:
````
// - load remote RDF document
var fetch = $rdf.fetcher(kb, 10000);
fetch.nowOrWhenFetched('http://dig.csail.mit.edu/2008/webdav/timbl/foaf.rdf', undefined, function(ok) {
    console.log(kb.statements);
});
````
The loaded triples will be printed, and the node program won't terminate before the timeout is reached...

**Comment by melvincarvalho** [comment]
I may have seen this before.  Trying to run:

    var $rdf = require('rdflib');

    g = $rdf.graph();
    f = $rdf.fetcher(g, 5000);

    f.nowOrWhenFetched('http://dig.csail.mit.edu/2008/webdav/timbl/foaf.rdf', undefined, function(ok) {
      console.log('Success!');
    });

Gives me:

    `jsdom 4.x onward only works on io.js, not Node.js™: https://github.com/tmpvar
    ^
    SyntaxError: Unexpected token ILLEGAL
        at Module._compile (module.js:439:25)
        at Object.Module._extensions..js (module.js:474:10)
        at Module.load (module.js:356:32)
        at Function.Module._load (module.js:312:12)
        at Module.require (module.js:364:17)
        at require (module.js:380:17)
        at Object.$rdf.Util.parseXML (/var/www/klaranet/wallet/github.com/linkeddata/node_modules/rdflib/dist/rdflib.js:351:21)
        at xhr.handle (/var/www/klaranet/wallet/github.com/linkeddata/node_modules/rdflib/dist/rdflib.js:24087:53)
        at null.onreadystatechange (/var/www/klaranet/wallet/github.com/linkeddata/node_modules/rdflib/dist/rdflib.js:25019:25)
        at dispatchEvent (/var/www/klaranet/wallet/github.com/linkeddata/node_modules/rdflib/node_modules/xmlhttprequest/lib/XMLHttpRequest.js:572:25)

**Comment by ckristo** [comment]
@melvincarvalho For the jsdom error, see #47 -- when I try to run your code, the same problem: the node command doesn't terminate before the timeout (5 seconds) are passed, although the success message is printed several seconds earlier

**Comment by melvincarvalho** [comment]
@ckristo thanks, that seems to work now

I can reproduce this error too

Some code where I've used it: https://github.com/gitpay/util/blob/master/commands/keys.js

I normally set the timeout to 2s which gives it time to return.

**Comment by jeswr** [comment]
Verified during the triage in #824: this issue was proposed for closure as stale/fixed, but on re-checking against **rdflib v2.4.0** the reported problem **still reproduces**, so I'm keeping it open and reclassifying it as an actionable bug rather than closing it. Details from the re-check: The reporter's primary case (loading a local file: URL) still hangs node until the configured timeout expires on v2.4.0: the fetch settles immediately but the pending setTimeout (src/fetcher.ts:2172) is never cleared on failure, holding the event loop open. Actionable fix: clear the request's timeouts in failFetch (mirroring the cleanupFetchRequest/clearTimeout logic at src/fetcher.ts:1017-1023). (Agent-assisted verification for @jeswr — see #824.)
