### ISSUE TITLE
$rdf.SPARQLToQuery with testMode = false -- TypeError: undefined is not a function

### ISSUE THREAD

**Issue by ckristo** [linkeddata/rdflib.js#70]
`$rdf.SPARQLToQuery` causes an error because it calls a non-existing function at `sparql.js:534,539` -- usage: `var query = $rdf.SPARQLToQuery(sparqlQuery, false, kb);`

````
/opt/local/bin/node sparql_example.js
/home/ckristo/examples/rdflib.js/node_modules/rdflib/dist/rdflib.js:5578
        if($rdf.fetcher) $rdf.fetcher.lookUpThing(st.subject,"sparql:"+st.subj
                                      ^
TypeError: undefined is not a function
    at Object.$rdf.SPARQLToQuery (/home/ckristo/examples/rdflib.js/node_modules/rdflib/dist/rdflib.js:5578:39)
    at null.userCallback (/home/ckristo/examples/rdflib.js/sparql_example.js:20:22)
    at doneFetch (/home/ckristo/examples/rdflib.js/node_modules/rdflib/dist/rdflib.js:24606:17)
````

**Comment by ckristo** [comment]
I don't know what the code that causes the error should do actually, but the only way of getting the needed fetcher instance that I see is to use the fetcher instance of the formula `kb` -- here's a quick fix, what do you think?

````javascript
// sparql.js:534
// old code: if($rdf.fetcher) $rdf.fetcher.lookUpThing(st.subject,"sparql:"+st.subject);
if(kb.fetcher) kb.fetcher.lookUpThing(st.subject,"sparql:"+st.subject);
// ...
// sparql.js:539
// old code: if($rdf.fetcher) $rdf.fetcher.lookUpThing(st.object,"sparql:"+st.object);
if(kb.fetcher) kb.fetcher.lookUpThing(st.object,"sparql:"+st.object);
````

**Comment by ckristo** [comment]
What I find strange though in the current version of `SPARQLToQuery` is that the formula instance `kb` is used only to create terms like symbols or bnodes. There are factory methods in `$rdf` for that...

**Comment by ckristo** [comment]
Duplicate of #111 (sorry for creating a new issue, thought that was fixed already).
