### ISSUE TITLE
rdflib cannot parse JSON-LD

### ISSUE THREAD

**Issue by jamsden** [linkeddata/rdflib.js#76]
I see rdflib loads jsonld.js and $rdf.parse references contentType application/json+ld. Shouldn't this be application/ld+json (which is the registered MIME type)?

<pre>
$rdf.parse(rs_json.toString(), kb2, catalogURI, 'application/ld+json');
</pre>

In any case, attempting to parse a JSON-LD file fails. application/ld+json gives an error that says it isn't supported. application/json+ld fails with:
<pre>
/Users/jamsden/Developer/node/node_modules/rdflib/dist/rdflib.js:25504
            callback(null, kb);
            ^
TypeError: callback is not a function
    at Object.tripleCallback [as _callback] (/Users/jamsden/Developer/node/node_modules/rdflib/dist/rdflib.js:25504:13)
    at Object.N3Parser._readInTopContext (/Users/jamsden/Developer/node/node_modules/rdflib/dist/rdflib.js:22690:19)
    at /Users/jamsden/Developer/node/node_modules/rdflib/dist/rdflib.js:23209:35
    at Object.N3Lexer._tokenizeToEnd (/Users/jamsden/Developer/node/node_modules/rdflib/dist/rdflib.js:22312:11)
    at Immediate._onImmediate (/Users/jamsden/Developer/node/node_modules/rdflib/dist/rdflib.js:22572:38)
    at processImmediate [as _immediateCallback] (timers.js:371:17)
</pre>

**Comment by martinmr** [comment]
The MIME error is corrected in HEAD and the latest npm version.
Because the libraries used to parse json-ld only work asynchronously, there is no support for synchronous parsing for nquads and JSON-LD. Instead you should call parse as:

```
$rdf.parse(rs_json.toString(), kb2, catalogURI, 'application/ld+json', function(err, kb) {
    //Your callback function
});
```

**Comment by jamsden** [comment]
Thank you very much!
